# üê≥ Docker Compose ‚Äî entorno desarrollo A4CO Fase 1
services:
  postgres:
    image: postgres:16
    container_name: a4co-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: a4co_dev
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: a4co-redis
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10
    container_name: a4co-nats
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  order-service:
    build:
      context: ../apps/order-service
      dockerfile: ../apps/order-service/Dockerfile
    container_name: a4co-order-service
    depends_on:
      - postgres
      - nats
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dev:dev@postgres:5432/a4co_dev?schema=orders_schema
      NATS_URL: nats://nats:4222
    ports:
      - "3001:3000"

  payment-service:
    build:
      context: ../apps/payment-service
      dockerfile: ../apps/payment-service/Dockerfile
    container_name: a4co-payment-service
    depends_on:
      - nats
    environment:
      NODE_ENV: development
      NATS_URL: nats://nats:4222
      STRIPE_KEY: sk_test_xxxxx
    ports:
      - "3002:3000"

  inventory-service:
    build:
      context: ../apps/inventory-service
      dockerfile: ../apps/inventory-service/Dockerfile
    container_name: a4co-inventory-service
    depends_on:
      - postgres
      - nats
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dev:dev@postgres:5432/a4co_dev?schema=inventory_schema
      NATS_URL: nats://nats:4222
    ports:
      - "3003:3000"
